// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: csrservice.proto

package csrserver

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CSRRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cn string `protobuf:"bytes,1,opt,name=cn,proto3" json:"cn,omitempty"`
}

func (x *CSRRequest) Reset() {
	*x = CSRRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_csrservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSRRequest) ProtoMessage() {}

func (x *CSRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_csrservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSRRequest.ProtoReflect.Descriptor instead.
func (*CSRRequest) Descriptor() ([]byte, []int) {
	return file_csrservice_proto_rawDescGZIP(), []int{0}
}

func (x *CSRRequest) GetCn() string {
	if x != nil {
		return x.Cn
	}
	return ""
}

type CSRResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cert string `protobuf:"bytes,1,opt,name=cert,proto3" json:"cert,omitempty"`
}

func (x *CSRResponse) Reset() {
	*x = CSRResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_csrservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSRResponse) ProtoMessage() {}

func (x *CSRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_csrservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSRResponse.ProtoReflect.Descriptor instead.
func (*CSRResponse) Descriptor() ([]byte, []int) {
	return file_csrservice_proto_rawDescGZIP(), []int{1}
}

func (x *CSRResponse) GetCert() string {
	if x != nil {
		return x.Cert
	}
	return ""
}

type SignCSRRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cn string `protobuf:"bytes,1,opt,name=cn,proto3" json:"cn,omitempty"`
}

func (x *SignCSRRequest) Reset() {
	*x = SignCSRRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_csrservice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignCSRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignCSRRequest) ProtoMessage() {}

func (x *SignCSRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_csrservice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignCSRRequest.ProtoReflect.Descriptor instead.
func (*SignCSRRequest) Descriptor() ([]byte, []int) {
	return file_csrservice_proto_rawDescGZIP(), []int{2}
}

func (x *SignCSRRequest) GetCn() string {
	if x != nil {
		return x.Cn
	}
	return ""
}

type SignCSRResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cert string `protobuf:"bytes,1,opt,name=cert,proto3" json:"cert,omitempty"`
}

func (x *SignCSRResponse) Reset() {
	*x = SignCSRResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_csrservice_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignCSRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignCSRResponse) ProtoMessage() {}

func (x *SignCSRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_csrservice_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignCSRResponse.ProtoReflect.Descriptor instead.
func (*SignCSRResponse) Descriptor() ([]byte, []int) {
	return file_csrservice_proto_rawDescGZIP(), []int{3}
}

func (x *SignCSRResponse) GetCert() string {
	if x != nil {
		return x.Cert
	}
	return ""
}

var File_csrservice_proto protoreflect.FileDescriptor

var file_csrservice_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x73, 0x72, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x09, 0x63, 0x73, 0x72, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x1c, 0x0a,
	0x0a, 0x43, 0x53, 0x52, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x63,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x63, 0x6e, 0x22, 0x21, 0x0a, 0x0b, 0x43,
	0x53, 0x52, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x65,
	0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x65, 0x72, 0x74, 0x22, 0x20,
	0x0a, 0x0e, 0x53, 0x69, 0x67, 0x6e, 0x43, 0x53, 0x52, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x63, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x63, 0x6e,
	0x22, 0x25, 0x0a, 0x0f, 0x53, 0x69, 0x67, 0x6e, 0x43, 0x53, 0x52, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x65, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x63, 0x65, 0x72, 0x74, 0x32, 0x8e, 0x01, 0x0a, 0x0a, 0x43, 0x53, 0x52, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3c, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x43, 0x53, 0x52, 0x12, 0x15, 0x2e, 0x63, 0x73, 0x72, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x43, 0x53, 0x52, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x63, 0x73, 0x72,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x53, 0x52, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x07, 0x53, 0x69, 0x67, 0x6e, 0x43, 0x53, 0x52, 0x12,
	0x19, 0x2e, 0x63, 0x73, 0x72, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x69, 0x67, 0x6e,
	0x43, 0x53, 0x52, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x63, 0x73, 0x72,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x43, 0x53, 0x52, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x5f, 0x0a, 0x20, 0x69, 0x6f, 0x2e, 0x7a,
	0x68, 0x65, 0x6e, 0x67, 0x79, 0x69, 0x31, 0x33, 0x2e, 0x63, 0x61, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x63, 0x73, 0x72, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x42, 0x0f, 0x43, 0x65,
	0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a,
	0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x68, 0x65, 0x6e,
	0x67, 0x79, 0x69, 0x31, 0x33, 0x2f, 0x63, 0x61, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x63, 0x73, 0x72, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_csrservice_proto_rawDescOnce sync.Once
	file_csrservice_proto_rawDescData = file_csrservice_proto_rawDesc
)

func file_csrservice_proto_rawDescGZIP() []byte {
	file_csrservice_proto_rawDescOnce.Do(func() {
		file_csrservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_csrservice_proto_rawDescData)
	})
	return file_csrservice_proto_rawDescData
}

var file_csrservice_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_csrservice_proto_goTypes = []interface{}{
	(*CSRRequest)(nil),      // 0: csrserver.CSRRequest
	(*CSRResponse)(nil),     // 1: csrserver.CSRResponse
	(*SignCSRRequest)(nil),  // 2: csrserver.SignCSRRequest
	(*SignCSRResponse)(nil), // 3: csrserver.SignCSRResponse
}
var file_csrservice_proto_depIdxs = []int32{
	0, // 0: csrserver.CSRService.CreateCSR:input_type -> csrserver.CSRRequest
	2, // 1: csrserver.CSRService.SignCSR:input_type -> csrserver.SignCSRRequest
	1, // 2: csrserver.CSRService.CreateCSR:output_type -> csrserver.CSRResponse
	3, // 3: csrserver.CSRService.SignCSR:output_type -> csrserver.SignCSRResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_csrservice_proto_init() }
func file_csrservice_proto_init() {
	if File_csrservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_csrservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSRRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_csrservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSRResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_csrservice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignCSRRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_csrservice_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignCSRResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_csrservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_csrservice_proto_goTypes,
		DependencyIndexes: file_csrservice_proto_depIdxs,
		MessageInfos:      file_csrservice_proto_msgTypes,
	}.Build()
	File_csrservice_proto = out.File
	file_csrservice_proto_rawDesc = nil
	file_csrservice_proto_goTypes = nil
	file_csrservice_proto_depIdxs = nil
}
